server:
  port: 4000
  
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:sqlserver://localhost:1433;DatabaseName=SAMPLE_DB;trustServerCertificate=true
    username: whnho
    password: Dnjsuddl1!
  devtools:
    livereload:
      enabled: true
      
mybatis:
  mapper-locations: classpath:/mapper/**/*.xml