server:
  port: 4000
  
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://192.168.0.12:5432/postgres
    username: postgres
    password: ishift7150!
  devtools:
    livereload:
      enabled: true
      
mybatis:
  mapper-locations: classpath:/mapper/**/*.xml